"""initial - M2 tables

Revision ID: 22d6dcbe6fee
Revises: 
Create Date: 2026-09-18 13:43:34.641384
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22d6dcbe6fee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='projectstatus', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('workspace_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Enum('hypothesis', 'awaiting_answers', 'fact_gate', 'key_message_gate', 'plan_review', 'approved', 'failed', name='sessionphase', native_enum=False, length=32), server_default='hypothesis', nullable=False),
    sa.Column('round_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('active', 'done', 'aborted', name='sessionstatus', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('pending_questions', sa.JSON(), nullable=True),
    sa.Column('pending_facts', sa.JSON(), nullable=True),
    sa.Column('pending_key_messages', sa.JSON(), nullable=True),
    sa.Column('checklist', sa.JSON(), nullable=True),
    sa.Column('key_messages_approved', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('hypothesis', sa.JSON(), nullable=True),
    sa.Column('llm_turns', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_project_id'), 'interview_sessions', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('derive_build', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'cancelled', name='jobstatus', native_enum=False, length=32), server_default='queued', nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_class', sa.Enum('validation', 'schema', 'llm', 'builder', 'internal', name='joberrorclass', native_enum=False, length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('docs', sa.JSON(), nullable=True),
    sa.Column('parsed_ok', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'superseded', name='planstatus', native_enum=False, length=32), server_default='draft', nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('origin', sa.Enum('interview', 'edit', name='planorigin', native_enum=False, length=32), server_default='interview', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_no', name='uq_project_planver')
    )
    op.create_index(op.f('ix_plans_project_id'), 'plans', ['project_id'], unique=False)
    op.create_table('derivatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('slides', 'report', name='derivativekind', native_enum=False, length=32), nullable=False),
    sa.Column('doc', sa.String(length=100), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.Column('slides_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sections_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unconfirmed', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_derivatives_plan_id'), 'derivatives', ['plan_id'], unique=False)
    op.create_index(op.f('ix_derivatives_project_id'), 'derivatives', ['project_id'], unique=False)
    op.create_table('facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=300), server_default='', nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='factstatus', native_enum=False, length=32), server_default='active', nullable=False),
    sa.Column('origin', sa.Enum('interview', 'review', 'manual', name='factorigin', native_enum=False, length=32), server_default='interview', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_project_id'), 'facts', ['project_id'], unique=False)
    op.create_table('interview_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', 'tool', 'event', name='messagerole', native_enum=False, length=32), nullable=False),
    sa.Column('kind', sa.Enum('text', 'questions', 'facts', 'key_messages', 'plan_draft', 'state', 'notice', 'error', 'tool_call', name='messagekind', native_enum=False, length=32), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_session_seq')
    )
    op.create_index(op.f('ix_interview_messages_session_id'), 'interview_messages', ['session_id'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('derivative_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('doc_kind', sa.String(length=100), nullable=False),
    sa.Column('ext', sa.String(length=8), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['derivative_id'], ['derivatives.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_derivative_id'), 'builds', ['derivative_id'], unique=False)
    op.create_index(op.f('ix_builds_plan_id'), 'builds', ['plan_id'], unique=False)
    op.create_index(op.f('ix_builds_project_id'), 'builds', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_builds_project_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_plan_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_derivative_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_interview_messages_session_id'), table_name='interview_messages')
    op.drop_table('interview_messages')
    op.drop_index(op.f('ix_facts_project_id'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_derivatives_project_id'), table_name='derivatives')
    op.drop_index(op.f('ix_derivatives_plan_id'), table_name='derivatives')
    op.drop_table('derivatives')
    op.drop_index(op.f('ix_plans_project_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_interview_sessions_project_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###